[package]
name = "zenos-init"
version = "0.1.0"
edition = "2024"

[dependencies]

[target.'cfg(target_os = "none")']
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-static",
    "-C", "link-arg=-no-pie",
    "-C", "panic=abort",
]




[[bin]]
name = "zenos-init"
path = "src/main.rs"
