[package]
name = "zenos"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "zenos-kernel",
    "zenos-bootloader",
    "zenos-bootloader/api",
    "zenos-bootloader/common",
    "zenos-bootloader/common/config",
    "zenos-bootloader/uefi",
    "zenos-init", "syscall-macro",
    "zenos-fuzz",
]

[workspace.package]
version = "0.1.0"
repository = "unknown"
license = "MIT"

[workspace.dependencies]
bootloader_api = { version = "0.1.0", path = "zenos-bootloader/api" }
bootloader-x86_64-common = { version = "0.1.0", path = "zenos-bootloader/common" }
bootloader-boot-config = { version = "0.1.0", path = "zenos-bootloader/common/config" }


[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"
zenos-bootloader = { path = "zenos-bootloader" }
clap = { version = "4.5.48", features = ["derive"] }

[profile.release]
debug-assertions = false

[profile.dev]
opt-level = 2
debug-assertions = true