[package]
name = "zenos-kernel"
version = "0.1.0"
edition = "2024"

[features]
default = []
color = []
test_stub = []

[dependencies]
bootloader_api = { workspace = true }
embedded-graphics = "0.8.1"
spin = "0.10.0"
heapless = "0.9.1"
x86_64 = "0.15.2"
uart_16550 = "0.4.0"
acpi = "5.2.0"
xmas-elf = "0.10.0"
pc-keyboard = "0.8.0"
linked_list_allocator = "0.10.1"
syscall_macro = { path = "../syscall-macro" }
bitflags = "2.10.0"
hashbrown = { version = "0.16.1" }

[dependencies.fatfs]
version = "0.4"
git = "https://github.com/rafalh/rust-fatfs/"
default-features = false
features = ["alloc", "log_level_debug"]

[dependencies.log]
version = "0.4.27"
default-features = false