[package]
name = "zenos-kernel"
version = "0.1.0"
edition = "2024"

[features]
default = []
color = []
test_stub = []
run-kunittest = []

[dependencies]
bootloader_api = { workspace = true }
arch-common = { version = "0.1.0", path = "arch/common" }
log = { version = "0.4.17", default-features = false }