[package]
name = "zenos-kernel"
version = "0.1.0"
edition = "2024"

[features]
default = []
__test_timer = []

[dependencies]
log = { version = "0.4.17", default-features = false }
bitflags = { version = "2.11.1", default-features = false }
kprimitives = { workspace = true }
kmm = {workspace = true}
kernel-macros = { workspace = true }
bootloader_api = { workspace = true }
uuid = { version = "1.26.0", default-features = false, features = ["v5"]}

[[bin]]
name = "zenos-kernel"
